name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!!"
      - name: list
        run: echo $ls
      - name: install-studio-cli
        run: INST_URL=https://distro.windriver.com/dist/wrstudio/wrstudio-cli-distro-cd/install-studio-cli.sh && curl -f $INST_URL --output inst.sh && bash inst.sh -u $INST_URL -y
      - name: version-check
        run: studio-cli --version
      - name: reserve-target-virtual
        run: studio-cli vlab virtual reserve --id dcb2335c-a923-4605-a642-5cecff88e450 --hours 1 --var artifact_path=workspace-se/builds/michael-foglia/zcu_102_TEST/2403/vip -a
      - name: reserve-target-physical
        run: echo "virtualId=$(studio-cli vlab physical reserve -i 4eb5d76c-6324-4bec-aba9-a8ff8a73a5fa | jq -r '.data.reservationId')"
      - name: execute-virtual
        run: studio-cli taf execution run -p 257185f9-04a7-43b4-8b5c-9503ad10a32e -f final.json
